---
namespace: fmjstudios
name: containers
version: 0.0.1
readme: README.md
authors:
  - Maximilian Gindorfer <info@fmj.dev>
description: Ansible collection for containers
license_file: "LICENSE"
tags:
  - containers
  - docker
  - docker-compose
  - kubernetes
  - portainer
  - traefik
  - docker-swarm
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: https://delta4x4.com
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore
  - LICENSE
  - Makefile
  - AUTHORS
  - .vscode
  - .github
